name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy to surge

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          domain: 'isael.surge.sh'
          project: C:\Users\Isael\Desktop\practica-devops\.
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
          
      - run: npm install -g surge
      - run: surge . ${{ secrets.SURGE_LOGIN }} --token ${{ secrets.SURGE_TOKEN }}